var BUBBLE_PARAMETERS = {
    "data_file": "satellites.csv",
    "report_title": "Every Satellite Orbiting the Earth",
    "footer_text": "All the Satellites orbitng the Earth.",
    "width": 940,
    "height": 500,
    "force_strength": 0.03,
    "force_type": "charge",
    "radius_field": "LaunchMass",
    "numeric_fields": ["Perigee", "Apogee", "Period", "DryMass", "Power", "LaunchMass", "Age"],
    "fill_color": {
        "data_field": "OperatorCountry",
        "color_groups": {
            "Algeria": "#d84b2a",
            "Argentina": "#beccae",
            "Australia": "#7aa25c",
            "Austria": "#0C090A",
            "Azerbaijan": "#34282C",
            "Bangladesh": "#25383C",
            "Belarus": "#5C5858",
            "Belgium": "#B6B6B4",
            "Bolivia": "#E5E4E2",
            "Brazil": "#98AFC7",
            "Bulgaria": "#6D7B8D",
            "Canada": "#566D7E",
            "Chile": "#737CA1",
            "China": "#2B547E",
            "China/Brazil": "#151B54",
            "Czech Republic": "#342D7E",
            "Denmark": "#0020C2",
            "Egypt": "#6960EC",
            "ESA": "#357EC7",
            "ESA/USA": "#659EC7",
            "ESA/USA/Russia": "#95B9C7",
            "Finland": "#6495ED",
            "France": "#38ACEC",
            "France/Belgium/Sweden": "#79BAEC",
            "France/Israel": "#A0CFEC",
            "France/Italy": "#B7CEEC",
            "France/Italy/Belgium/Spain/Greece": "#C6DEFF",
            "France/USA": "#AFDCEC",
            "Germany": "#BDEDFF",
            "Germany/USA": "#CFECEC",
            "Greece": "#CCFFFF",
            "Greece/United Kingdom": "#9AFEFF",
            "India": "#7FFFD4",
            "India/Canada": "#00FFFF",
            "India/France": "#8EEBEC",
            "Indonesia": "#81D8D0",
            "Iran": "#77BFC7",
            "Iraq": "#7BCCB5",
            "Israel": "#48CCCD",
            "Italy": "#3EA99F",
            "Japan": "#3B9C9C",
            "Kazakhstan": "#438D80",
            "Laos": "#5E7D7E",
            "Latvia": "#008080",
            "Lithuania": "#4E8975",
            "Luxembourg": "#78866B",
            "Malaysia": "#848b79",
            "Mexico": "#728C00",
            "Mongolia": "#254117",
            "Morocco/Germany": "#347235",
            "Multinational": "#387C44",
            "Netherlands": "#4E9258",
            "Nigeria": "#6AA121",
            "Norway": "#52D017",
            "Pakistan": "#99C68E",
            "Peru": "#8BB381",
            "Russia": "#B2C248",
            "Russia/Multinational": "#7FE817",
            "Russia/USA": "#64E986",
            "Saudi Arabia": "#87F717",
            "Singapore": "#B5EAAA",
            "Singapore/Japan": "#EDDA74",
            "Singapore/Taiwan": "#EDE275",
            "Slovakia": "#FFFF00",
            "South Africa": "#FFF8C6",
            "South Korea": "#FAEBD7",
            "Spain": "#F3E5AB",
            "Sweden": "#FFE5B4",
            "Switzerland": "#FFDB58",
            "Taiwan": "#EAC117",
            "Taiwan/USA": "#F2BB66",
            "Thailand": "#FBB917",
            "Turkey": "#FFA62F",
            "Turkey/France": "#E2A76F",
            "Turkmenistan/Monaco": "#FFCBA4",
            "Ukraine": "#C9BE62",
            "Ukraine/China": "#D4A017",
            "United Arab Emirates": "#CD7F32",
            "United Kingdom": "#966F33",
            "United Kingdom/ESA": "#806517",
            "Uruguay": "#827B60",
            "USA": "#493D26",
            "USA/Argentina": "#6F4E37",
            "USA/Canada": "#7F462C",
            "USA/Canada/Japan": "#7F462C",
            "USA/France": "#F87217",
            "USA/Japan": "#F75D59",
            "USA/Japan/Brazil": "#FF0000",
            "USA/Russia": "#9F000F",
            "USA/United Kingdom/Italy": "#7E3517",
            "Venezuela": "#800517",
            "Vietnam": "#7F525D"
        }
    },
    "tooltip": [
        {"title": "Satellite Name", "data_field": "SatelliteName"},
        {"title": "Operator Country", "data_field": "OperatorCountry"},
        {"title": "Orbit Class", "data_field": "OrbitClass"},
        {"title": "Perigee", "data_field": "Perigee"},
        {"title": "Apogee", "data_field": "Apogee"},
        {"title": "Launch Mass", "data_field": "LaunchMass"},
        {"title": "Age", "data_field": "Age"},
        {"title": "ContractorCountry", "data_field": "ContractorCountry"},
        {"title": "Launch Date", "data_field": "LaunchDate"},
    ],
    "modes": [
        {
            "button_text": "All Satellites",
            "button_id": "all",
            "type": "grid",
            "labels": null,
            "grid_dimensions": {"rows": 1, "columns": 1},
            "data_field": null
        },
        {
            "button_text": "Satellites by Usage Type",
            "button_id": "usage",
            "type": "grid",
            "labels": ["Civil", "Commercial", "Commercial/Government", "Commercial/Military", "Government", "Government/Commercial", "Government/Military", "Military", "Military/Civil","Military/Commercial","Military/Government"],
            "grid_dimensions": {"rows": 3, "columns": 4},
            "data_field": "Users"
        },
        {
            "button_text": "Satelites by Purpose",
            "button_id": "purpose",
            "type": "grid",
            "labels": ["Communications", "Earth Observation", "Earth Science", "Navigation", "Space Observation", "Space Science", "Technology Demonstration", "Technology Development"],
            "grid_dimensions": {"rows": 3, "columns": 3},
            "data_field": "Purpose"
        },
        {
            "button_text": "Orbit Class",
            "button_id": "orbitClass",
            "type": "grid",
            "labels": ["Elliptical", "GEO", "LEO", "MEO"],
            "grid_dimensions": {"rows": 1, "columns": 4},
            "data_field": "OrbitClass"
        },
        {
            "button_text": "Orbit Type",
            "button_id": "orbitType",
            "type": "grid",
            "labels": ["Cislunar", "Deep Highly Eccentric", "Elliptical", "Equatorial", "Molniya", "Non-Polar Inclined", "None", "Polar", "Sun-Synchronous"],
            "grid_dimensions": {"rows": 3, "columns": 3},
            "data_field": "OrbitType"
        },
        {
            "button_text": "Apogee vs Perigee",
            "button_id": "ApogeePerigee",
            "type": "scatterplot",
            "x_data_field": "Apogee",
            "y_data_field": "Perigee",
            "x_format_string": ",.2r",
            "y_format_string": ",.2r"
        }
    ]
};